name: Update URLS
on:
  push
jobs:
  updateURLS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: moritzLanger/ide-urls
          path: ide-urls
          token: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          cd cli
          mvn -B -ntp -Dstyle.color=always install
          mvn -B -ntp -Dstyle.color=always exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="../ide-urls PT5H30M"| tee log.txt
          sed -n '/ERROR REPORT FROM/,/ERROR REPORT ENDS/p' log.txt > error_report.txt
          cat error_report.txt
      - name: ls
        run: ls -lR
      - name: Read log file
        id: getLogContent
        uses: andstor/file-reader-action@v1
        with:
          path: "./cli/logs/logfile.log"
      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: URL Update report
          summary: Failiure
          text:  ${{ steps.getLogContent.outputs.contents }}          
      - name: Commit and push to ide-urls
        run: |
          cd ide-urls
          git config --global user.name ${{ secrets.BUILD_USER }}
          git config --global user.email ${{ secrets.BUILD_USER_EMAIL }}
          if [ "$(git status -z)" = "" ]
          then
            echo "No changes, nothing to commit."
          else
            git add .
            git commit -m "Update urls"
            git push
          fi

   
